# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bazola-ai/dev/baz-code/hexagotchi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bazola-ai/dev/baz-code/hexagotchi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bazola-ai/dev/baz-code/hexagotchi/CMakeFiles /home/bazola-ai/dev/baz-code/hexagotchi//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bazola-ai/dev/baz-code/hexagotchi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_merge_controller

# Build rule for target.
test_merge_controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_merge_controller
.PHONY : test_merge_controller

# fast build rule for target.
test_merge_controller/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/build
.PHONY : test_merge_controller/fast

#=============================================================================
# Target rules for targets named test_story_sequencer

# Build rule for target.
test_story_sequencer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_story_sequencer
.PHONY : test_story_sequencer

# fast build rule for target.
test_story_sequencer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/build
.PHONY : test_story_sequencer/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named raylib-web

# Build rule for target.
raylib-web: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib-web
.PHONY : raylib-web

# fast build rule for target.
raylib-web/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib-web.dir/build.make CMakeFiles/raylib-web.dir/build
.PHONY : raylib-web/fast

#=============================================================================
# Target rules for targets named game-web

# Build rule for target.
game-web: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game-web
.PHONY : game-web

# fast build rule for target.
game-web/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game-web.dir/build.make CMakeFiles/game-web.dir/build
.PHONY : game-web/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f glfw/CMakeFiles/uninstall.dir/build.make glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f glfw/src/CMakeFiles/glfw.dir/build.make glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f glfw/src/CMakeFiles/update_mappings.dir/build.make glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

raylib/src/raudio.o: raylib/src/raudio.c.o
.PHONY : raylib/src/raudio.o

# target to build an object file
raylib/src/raudio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/raudio.c.o
.PHONY : raylib/src/raudio.c.o

raylib/src/raudio.i: raylib/src/raudio.c.i
.PHONY : raylib/src/raudio.i

# target to preprocess a source file
raylib/src/raudio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/raudio.c.i
.PHONY : raylib/src/raudio.c.i

raylib/src/raudio.s: raylib/src/raudio.c.s
.PHONY : raylib/src/raudio.s

# target to generate assembly for a file
raylib/src/raudio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/raudio.c.s
.PHONY : raylib/src/raudio.c.s

raylib/src/rcore.o: raylib/src/rcore.c.o
.PHONY : raylib/src/rcore.o

# target to build an object file
raylib/src/rcore.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rcore.c.o
.PHONY : raylib/src/rcore.c.o

raylib/src/rcore.i: raylib/src/rcore.c.i
.PHONY : raylib/src/rcore.i

# target to preprocess a source file
raylib/src/rcore.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rcore.c.i
.PHONY : raylib/src/rcore.c.i

raylib/src/rcore.s: raylib/src/rcore.c.s
.PHONY : raylib/src/rcore.s

# target to generate assembly for a file
raylib/src/rcore.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rcore.c.s
.PHONY : raylib/src/rcore.c.s

raylib/src/rmodels.o: raylib/src/rmodels.c.o
.PHONY : raylib/src/rmodels.o

# target to build an object file
raylib/src/rmodels.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rmodels.c.o
.PHONY : raylib/src/rmodels.c.o

raylib/src/rmodels.i: raylib/src/rmodels.c.i
.PHONY : raylib/src/rmodels.i

# target to preprocess a source file
raylib/src/rmodels.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rmodels.c.i
.PHONY : raylib/src/rmodels.c.i

raylib/src/rmodels.s: raylib/src/rmodels.c.s
.PHONY : raylib/src/rmodels.s

# target to generate assembly for a file
raylib/src/rmodels.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rmodels.c.s
.PHONY : raylib/src/rmodels.c.s

raylib/src/rshapes.o: raylib/src/rshapes.c.o
.PHONY : raylib/src/rshapes.o

# target to build an object file
raylib/src/rshapes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rshapes.c.o
.PHONY : raylib/src/rshapes.c.o

raylib/src/rshapes.i: raylib/src/rshapes.c.i
.PHONY : raylib/src/rshapes.i

# target to preprocess a source file
raylib/src/rshapes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rshapes.c.i
.PHONY : raylib/src/rshapes.c.i

raylib/src/rshapes.s: raylib/src/rshapes.c.s
.PHONY : raylib/src/rshapes.s

# target to generate assembly for a file
raylib/src/rshapes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rshapes.c.s
.PHONY : raylib/src/rshapes.c.s

raylib/src/rtext.o: raylib/src/rtext.c.o
.PHONY : raylib/src/rtext.o

# target to build an object file
raylib/src/rtext.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rtext.c.o
.PHONY : raylib/src/rtext.c.o

raylib/src/rtext.i: raylib/src/rtext.c.i
.PHONY : raylib/src/rtext.i

# target to preprocess a source file
raylib/src/rtext.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rtext.c.i
.PHONY : raylib/src/rtext.c.i

raylib/src/rtext.s: raylib/src/rtext.c.s
.PHONY : raylib/src/rtext.s

# target to generate assembly for a file
raylib/src/rtext.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rtext.c.s
.PHONY : raylib/src/rtext.c.s

raylib/src/rtextures.o: raylib/src/rtextures.c.o
.PHONY : raylib/src/rtextures.o

# target to build an object file
raylib/src/rtextures.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rtextures.c.o
.PHONY : raylib/src/rtextures.c.o

raylib/src/rtextures.i: raylib/src/rtextures.c.i
.PHONY : raylib/src/rtextures.i

# target to preprocess a source file
raylib/src/rtextures.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rtextures.c.i
.PHONY : raylib/src/rtextures.c.i

raylib/src/rtextures.s: raylib/src/rtextures.c.s
.PHONY : raylib/src/rtextures.s

# target to generate assembly for a file
raylib/src/rtextures.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raylib.dir/build.make CMakeFiles/raylib.dir/raylib/src/rtextures.c.s
.PHONY : raylib/src/rtextures.c.s

src/effects/CityWindowEffect.o: src/effects/CityWindowEffect.cpp.o
.PHONY : src/effects/CityWindowEffect.o

# target to build an object file
src/effects/CityWindowEffect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/CityWindowEffect.cpp.o
.PHONY : src/effects/CityWindowEffect.cpp.o

src/effects/CityWindowEffect.i: src/effects/CityWindowEffect.cpp.i
.PHONY : src/effects/CityWindowEffect.i

# target to preprocess a source file
src/effects/CityWindowEffect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/CityWindowEffect.cpp.i
.PHONY : src/effects/CityWindowEffect.cpp.i

src/effects/CityWindowEffect.s: src/effects/CityWindowEffect.cpp.s
.PHONY : src/effects/CityWindowEffect.s

# target to generate assembly for a file
src/effects/CityWindowEffect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/CityWindowEffect.cpp.s
.PHONY : src/effects/CityWindowEffect.cpp.s

src/effects/GrimeShader.o: src/effects/GrimeShader.cpp.o
.PHONY : src/effects/GrimeShader.o

# target to build an object file
src/effects/GrimeShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/effects/GrimeShader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/GrimeShader.cpp.o
.PHONY : src/effects/GrimeShader.cpp.o

src/effects/GrimeShader.i: src/effects/GrimeShader.cpp.i
.PHONY : src/effects/GrimeShader.i

# target to preprocess a source file
src/effects/GrimeShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/effects/GrimeShader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/GrimeShader.cpp.i
.PHONY : src/effects/GrimeShader.cpp.i

src/effects/GrimeShader.s: src/effects/GrimeShader.cpp.s
.PHONY : src/effects/GrimeShader.s

# target to generate assembly for a file
src/effects/GrimeShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/effects/GrimeShader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/GrimeShader.cpp.s
.PHONY : src/effects/GrimeShader.cpp.s

src/effects/JetMesh.o: src/effects/JetMesh.cpp.o
.PHONY : src/effects/JetMesh.o

# target to build an object file
src/effects/JetMesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/JetMesh.cpp.o
.PHONY : src/effects/JetMesh.cpp.o

src/effects/JetMesh.i: src/effects/JetMesh.cpp.i
.PHONY : src/effects/JetMesh.i

# target to preprocess a source file
src/effects/JetMesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/JetMesh.cpp.i
.PHONY : src/effects/JetMesh.cpp.i

src/effects/JetMesh.s: src/effects/JetMesh.cpp.s
.PHONY : src/effects/JetMesh.s

# target to generate assembly for a file
src/effects/JetMesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/JetMesh.cpp.s
.PHONY : src/effects/JetMesh.cpp.s

src/effects/LitShader.o: src/effects/LitShader.cpp.o
.PHONY : src/effects/LitShader.o

# target to build an object file
src/effects/LitShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/LitShader.cpp.o
.PHONY : src/effects/LitShader.cpp.o

src/effects/LitShader.i: src/effects/LitShader.cpp.i
.PHONY : src/effects/LitShader.i

# target to preprocess a source file
src/effects/LitShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/LitShader.cpp.i
.PHONY : src/effects/LitShader.cpp.i

src/effects/LitShader.s: src/effects/LitShader.cpp.s
.PHONY : src/effects/LitShader.s

# target to generate assembly for a file
src/effects/LitShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/LitShader.cpp.s
.PHONY : src/effects/LitShader.cpp.s

src/effects/MoonEffect.o: src/effects/MoonEffect.cpp.o
.PHONY : src/effects/MoonEffect.o

# target to build an object file
src/effects/MoonEffect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/MoonEffect.cpp.o
.PHONY : src/effects/MoonEffect.cpp.o

src/effects/MoonEffect.i: src/effects/MoonEffect.cpp.i
.PHONY : src/effects/MoonEffect.i

# target to preprocess a source file
src/effects/MoonEffect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/MoonEffect.cpp.i
.PHONY : src/effects/MoonEffect.cpp.i

src/effects/MoonEffect.s: src/effects/MoonEffect.cpp.s
.PHONY : src/effects/MoonEffect.s

# target to generate assembly for a file
src/effects/MoonEffect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/MoonEffect.cpp.s
.PHONY : src/effects/MoonEffect.cpp.s

src/effects/SchoolSkyEffect.o: src/effects/SchoolSkyEffect.cpp.o
.PHONY : src/effects/SchoolSkyEffect.o

# target to build an object file
src/effects/SchoolSkyEffect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/SchoolSkyEffect.cpp.o
.PHONY : src/effects/SchoolSkyEffect.cpp.o

src/effects/SchoolSkyEffect.i: src/effects/SchoolSkyEffect.cpp.i
.PHONY : src/effects/SchoolSkyEffect.i

# target to preprocess a source file
src/effects/SchoolSkyEffect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/SchoolSkyEffect.cpp.i
.PHONY : src/effects/SchoolSkyEffect.cpp.i

src/effects/SchoolSkyEffect.s: src/effects/SchoolSkyEffect.cpp.s
.PHONY : src/effects/SchoolSkyEffect.s

# target to generate assembly for a file
src/effects/SchoolSkyEffect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/SchoolSkyEffect.cpp.s
.PHONY : src/effects/SchoolSkyEffect.cpp.s

src/effects/StarfieldEffect.o: src/effects/StarfieldEffect.cpp.o
.PHONY : src/effects/StarfieldEffect.o

# target to build an object file
src/effects/StarfieldEffect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/StarfieldEffect.cpp.o
.PHONY : src/effects/StarfieldEffect.cpp.o

src/effects/StarfieldEffect.i: src/effects/StarfieldEffect.cpp.i
.PHONY : src/effects/StarfieldEffect.i

# target to preprocess a source file
src/effects/StarfieldEffect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/StarfieldEffect.cpp.i
.PHONY : src/effects/StarfieldEffect.cpp.i

src/effects/StarfieldEffect.s: src/effects/StarfieldEffect.cpp.s
.PHONY : src/effects/StarfieldEffect.s

# target to generate assembly for a file
src/effects/StarfieldEffect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/effects/StarfieldEffect.cpp.s
.PHONY : src/effects/StarfieldEffect.cpp.s

src/engine/AssetPack.o: src/engine/AssetPack.cpp.o
.PHONY : src/engine/AssetPack.o

# target to build an object file
src/engine/AssetPack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/AssetPack.cpp.o
.PHONY : src/engine/AssetPack.cpp.o

src/engine/AssetPack.i: src/engine/AssetPack.cpp.i
.PHONY : src/engine/AssetPack.i

# target to preprocess a source file
src/engine/AssetPack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/AssetPack.cpp.i
.PHONY : src/engine/AssetPack.cpp.i

src/engine/AssetPack.s: src/engine/AssetPack.cpp.s
.PHONY : src/engine/AssetPack.s

# target to generate assembly for a file
src/engine/AssetPack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/AssetPack.cpp.s
.PHONY : src/engine/AssetPack.cpp.s

src/engine/Button.o: src/engine/Button.cpp.o
.PHONY : src/engine/Button.o

# target to build an object file
src/engine/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/Button.cpp.o
.PHONY : src/engine/Button.cpp.o

src/engine/Button.i: src/engine/Button.cpp.i
.PHONY : src/engine/Button.i

# target to preprocess a source file
src/engine/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/Button.cpp.i
.PHONY : src/engine/Button.cpp.i

src/engine/Button.s: src/engine/Button.cpp.s
.PHONY : src/engine/Button.s

# target to generate assembly for a file
src/engine/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/Button.cpp.s
.PHONY : src/engine/Button.cpp.s

src/engine/DialogBox.o: src/engine/DialogBox.cpp.o
.PHONY : src/engine/DialogBox.o

# target to build an object file
src/engine/DialogBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/DialogBox.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/DialogBox.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/DialogBox.cpp.o
.PHONY : src/engine/DialogBox.cpp.o

src/engine/DialogBox.i: src/engine/DialogBox.cpp.i
.PHONY : src/engine/DialogBox.i

# target to preprocess a source file
src/engine/DialogBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/DialogBox.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/DialogBox.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/DialogBox.cpp.i
.PHONY : src/engine/DialogBox.cpp.i

src/engine/DialogBox.s: src/engine/DialogBox.cpp.s
.PHONY : src/engine/DialogBox.s

# target to generate assembly for a file
src/engine/DialogBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/DialogBox.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/DialogBox.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/DialogBox.cpp.s
.PHONY : src/engine/DialogBox.cpp.s

src/engine/GameState.o: src/engine/GameState.cpp.o
.PHONY : src/engine/GameState.o

# target to build an object file
src/engine/GameState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/GameState.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/GameState.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/GameState.cpp.o
.PHONY : src/engine/GameState.cpp.o

src/engine/GameState.i: src/engine/GameState.cpp.i
.PHONY : src/engine/GameState.i

# target to preprocess a source file
src/engine/GameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/GameState.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/GameState.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/GameState.cpp.i
.PHONY : src/engine/GameState.cpp.i

src/engine/GameState.s: src/engine/GameState.cpp.s
.PHONY : src/engine/GameState.s

# target to generate assembly for a file
src/engine/GameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/GameState.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/GameState.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/GameState.cpp.s
.PHONY : src/engine/GameState.cpp.s

src/engine/HexTile.o: src/engine/HexTile.cpp.o
.PHONY : src/engine/HexTile.o

# target to build an object file
src/engine/HexTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/HexTile.cpp.o
.PHONY : src/engine/HexTile.cpp.o

src/engine/HexTile.i: src/engine/HexTile.cpp.i
.PHONY : src/engine/HexTile.i

# target to preprocess a source file
src/engine/HexTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/HexTile.cpp.i
.PHONY : src/engine/HexTile.cpp.i

src/engine/HexTile.s: src/engine/HexTile.cpp.s
.PHONY : src/engine/HexTile.s

# target to generate assembly for a file
src/engine/HexTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/HexTile.cpp.s
.PHONY : src/engine/HexTile.cpp.s

src/engine/HexWorld.o: src/engine/HexWorld.cpp.o
.PHONY : src/engine/HexWorld.o

# target to build an object file
src/engine/HexWorld.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/HexWorld.cpp.o
.PHONY : src/engine/HexWorld.cpp.o

src/engine/HexWorld.i: src/engine/HexWorld.cpp.i
.PHONY : src/engine/HexWorld.i

# target to preprocess a source file
src/engine/HexWorld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/HexWorld.cpp.i
.PHONY : src/engine/HexWorld.cpp.i

src/engine/HexWorld.s: src/engine/HexWorld.cpp.s
.PHONY : src/engine/HexWorld.s

# target to generate assembly for a file
src/engine/HexWorld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/HexWorld.cpp.s
.PHONY : src/engine/HexWorld.cpp.s

src/engine/SaveManager.o: src/engine/SaveManager.cpp.o
.PHONY : src/engine/SaveManager.o

# target to build an object file
src/engine/SaveManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SaveManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SaveManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SaveManager.cpp.o
.PHONY : src/engine/SaveManager.cpp.o

src/engine/SaveManager.i: src/engine/SaveManager.cpp.i
.PHONY : src/engine/SaveManager.i

# target to preprocess a source file
src/engine/SaveManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SaveManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SaveManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SaveManager.cpp.i
.PHONY : src/engine/SaveManager.cpp.i

src/engine/SaveManager.s: src/engine/SaveManager.cpp.s
.PHONY : src/engine/SaveManager.s

# target to generate assembly for a file
src/engine/SaveManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SaveManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SaveManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SaveManager.cpp.s
.PHONY : src/engine/SaveManager.cpp.s

src/engine/Scene.o: src/engine/Scene.cpp.o
.PHONY : src/engine/Scene.o

# target to build an object file
src/engine/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/Scene.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/Scene.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/Scene.cpp.o
.PHONY : src/engine/Scene.cpp.o

src/engine/Scene.i: src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.i

# target to preprocess a source file
src/engine/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/Scene.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/Scene.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.cpp.i

src/engine/Scene.s: src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.s

# target to generate assembly for a file
src/engine/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/Scene.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/Scene.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.cpp.s

src/engine/SceneActor.o: src/engine/SceneActor.cpp.o
.PHONY : src/engine/SceneActor.o

# target to build an object file
src/engine/SceneActor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneActor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneActor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneActor.cpp.o
.PHONY : src/engine/SceneActor.cpp.o

src/engine/SceneActor.i: src/engine/SceneActor.cpp.i
.PHONY : src/engine/SceneActor.i

# target to preprocess a source file
src/engine/SceneActor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneActor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneActor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneActor.cpp.i
.PHONY : src/engine/SceneActor.cpp.i

src/engine/SceneActor.s: src/engine/SceneActor.cpp.s
.PHONY : src/engine/SceneActor.s

# target to generate assembly for a file
src/engine/SceneActor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneActor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneActor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneActor.cpp.s
.PHONY : src/engine/SceneActor.cpp.s

src/engine/SceneCamera.o: src/engine/SceneCamera.cpp.o
.PHONY : src/engine/SceneCamera.o

# target to build an object file
src/engine/SceneCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneCamera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneCamera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneCamera.cpp.o
.PHONY : src/engine/SceneCamera.cpp.o

src/engine/SceneCamera.i: src/engine/SceneCamera.cpp.i
.PHONY : src/engine/SceneCamera.i

# target to preprocess a source file
src/engine/SceneCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneCamera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneCamera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneCamera.cpp.i
.PHONY : src/engine/SceneCamera.cpp.i

src/engine/SceneCamera.s: src/engine/SceneCamera.cpp.s
.PHONY : src/engine/SceneCamera.s

# target to generate assembly for a file
src/engine/SceneCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneCamera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneCamera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneCamera.cpp.s
.PHONY : src/engine/SceneCamera.cpp.s

src/engine/SceneInputHandler.o: src/engine/SceneInputHandler.cpp.o
.PHONY : src/engine/SceneInputHandler.o

# target to build an object file
src/engine/SceneInputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneInputHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneInputHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneInputHandler.cpp.o
.PHONY : src/engine/SceneInputHandler.cpp.o

src/engine/SceneInputHandler.i: src/engine/SceneInputHandler.cpp.i
.PHONY : src/engine/SceneInputHandler.i

# target to preprocess a source file
src/engine/SceneInputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneInputHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneInputHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneInputHandler.cpp.i
.PHONY : src/engine/SceneInputHandler.cpp.i

src/engine/SceneInputHandler.s: src/engine/SceneInputHandler.cpp.s
.PHONY : src/engine/SceneInputHandler.s

# target to generate assembly for a file
src/engine/SceneInputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneInputHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneInputHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneInputHandler.cpp.s
.PHONY : src/engine/SceneInputHandler.cpp.s

src/engine/SceneManager.o: src/engine/SceneManager.cpp.o
.PHONY : src/engine/SceneManager.o

# target to build an object file
src/engine/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneManager.cpp.o
.PHONY : src/engine/SceneManager.cpp.o

src/engine/SceneManager.i: src/engine/SceneManager.cpp.i
.PHONY : src/engine/SceneManager.i

# target to preprocess a source file
src/engine/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneManager.cpp.i
.PHONY : src/engine/SceneManager.cpp.i

src/engine/SceneManager.s: src/engine/SceneManager.cpp.s
.PHONY : src/engine/SceneManager.s

# target to generate assembly for a file
src/engine/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/engine/SceneManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/engine/SceneManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/SceneManager.cpp.s
.PHONY : src/engine/SceneManager.cpp.s

src/engine/TileType.o: src/engine/TileType.cpp.o
.PHONY : src/engine/TileType.o

# target to build an object file
src/engine/TileType.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/TileType.cpp.o
.PHONY : src/engine/TileType.cpp.o

src/engine/TileType.i: src/engine/TileType.cpp.i
.PHONY : src/engine/TileType.i

# target to preprocess a source file
src/engine/TileType.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/TileType.cpp.i
.PHONY : src/engine/TileType.cpp.i

src/engine/TileType.s: src/engine/TileType.cpp.s
.PHONY : src/engine/TileType.s

# target to generate assembly for a file
src/engine/TileType.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/TileType.cpp.s
.PHONY : src/engine/TileType.cpp.s

src/events/EventBus.o: src/events/EventBus.cpp.o
.PHONY : src/events/EventBus.o

# target to build an object file
src/events/EventBus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/events/EventBus.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/events/EventBus.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/events/EventBus.cpp.o
.PHONY : src/events/EventBus.cpp.o

src/events/EventBus.i: src/events/EventBus.cpp.i
.PHONY : src/events/EventBus.i

# target to preprocess a source file
src/events/EventBus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/events/EventBus.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/events/EventBus.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/events/EventBus.cpp.i
.PHONY : src/events/EventBus.cpp.i

src/events/EventBus.s: src/events/EventBus.cpp.s
.PHONY : src/events/EventBus.s

# target to generate assembly for a file
src/events/EventBus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/events/EventBus.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/events/EventBus.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/events/EventBus.cpp.s
.PHONY : src/events/EventBus.cpp.s

src/game/ApartmentScene.o: src/game/ApartmentScene.cpp.o
.PHONY : src/game/ApartmentScene.o

# target to build an object file
src/game/ApartmentScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ApartmentScene.cpp.o
.PHONY : src/game/ApartmentScene.cpp.o

src/game/ApartmentScene.i: src/game/ApartmentScene.cpp.i
.PHONY : src/game/ApartmentScene.i

# target to preprocess a source file
src/game/ApartmentScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ApartmentScene.cpp.i
.PHONY : src/game/ApartmentScene.cpp.i

src/game/ApartmentScene.s: src/game/ApartmentScene.cpp.s
.PHONY : src/game/ApartmentScene.s

# target to generate assembly for a file
src/game/ApartmentScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ApartmentScene.cpp.s
.PHONY : src/game/ApartmentScene.cpp.s

src/game/BossScene.o: src/game/BossScene.cpp.o
.PHONY : src/game/BossScene.o

# target to build an object file
src/game/BossScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/BossScene.cpp.o
.PHONY : src/game/BossScene.cpp.o

src/game/BossScene.i: src/game/BossScene.cpp.i
.PHONY : src/game/BossScene.i

# target to preprocess a source file
src/game/BossScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/BossScene.cpp.i
.PHONY : src/game/BossScene.cpp.i

src/game/BossScene.s: src/game/BossScene.cpp.s
.PHONY : src/game/BossScene.s

# target to generate assembly for a file
src/game/BossScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/BossScene.cpp.s
.PHONY : src/game/BossScene.cpp.s

src/game/ControlsOverlay.o: src/game/ControlsOverlay.cpp.o
.PHONY : src/game/ControlsOverlay.o

# target to build an object file
src/game/ControlsOverlay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ControlsOverlay.cpp.o
.PHONY : src/game/ControlsOverlay.cpp.o

src/game/ControlsOverlay.i: src/game/ControlsOverlay.cpp.i
.PHONY : src/game/ControlsOverlay.i

# target to preprocess a source file
src/game/ControlsOverlay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ControlsOverlay.cpp.i
.PHONY : src/game/ControlsOverlay.cpp.i

src/game/ControlsOverlay.s: src/game/ControlsOverlay.cpp.s
.PHONY : src/game/ControlsOverlay.s

# target to generate assembly for a file
src/game/ControlsOverlay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ControlsOverlay.cpp.s
.PHONY : src/game/ControlsOverlay.cpp.s

src/game/GameScene.o: src/game/GameScene.cpp.o
.PHONY : src/game/GameScene.o

# target to build an object file
src/game/GameScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GameScene.cpp.o
.PHONY : src/game/GameScene.cpp.o

src/game/GameScene.i: src/game/GameScene.cpp.i
.PHONY : src/game/GameScene.i

# target to preprocess a source file
src/game/GameScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GameScene.cpp.i
.PHONY : src/game/GameScene.cpp.i

src/game/GameScene.s: src/game/GameScene.cpp.s
.PHONY : src/game/GameScene.s

# target to generate assembly for a file
src/game/GameScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GameScene.cpp.s
.PHONY : src/game/GameScene.cpp.s

src/game/Gotchi.o: src/game/Gotchi.cpp.o
.PHONY : src/game/Gotchi.o

# target to build an object file
src/game/Gotchi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/Gotchi.cpp.o
.PHONY : src/game/Gotchi.cpp.o

src/game/Gotchi.i: src/game/Gotchi.cpp.i
.PHONY : src/game/Gotchi.i

# target to preprocess a source file
src/game/Gotchi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/Gotchi.cpp.i
.PHONY : src/game/Gotchi.cpp.i

src/game/Gotchi.s: src/game/Gotchi.cpp.s
.PHONY : src/game/Gotchi.s

# target to generate assembly for a file
src/game/Gotchi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/Gotchi.cpp.s
.PHONY : src/game/Gotchi.cpp.s

src/game/GotchiMood.o: src/game/GotchiMood.cpp.o
.PHONY : src/game/GotchiMood.o

# target to build an object file
src/game/GotchiMood.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiMood.cpp.o
.PHONY : src/game/GotchiMood.cpp.o

src/game/GotchiMood.i: src/game/GotchiMood.cpp.i
.PHONY : src/game/GotchiMood.i

# target to preprocess a source file
src/game/GotchiMood.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiMood.cpp.i
.PHONY : src/game/GotchiMood.cpp.i

src/game/GotchiMood.s: src/game/GotchiMood.cpp.s
.PHONY : src/game/GotchiMood.s

# target to generate assembly for a file
src/game/GotchiMood.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiMood.cpp.s
.PHONY : src/game/GotchiMood.cpp.s

src/game/GotchiScene.o: src/game/GotchiScene.cpp.o
.PHONY : src/game/GotchiScene.o

# target to build an object file
src/game/GotchiScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiScene.cpp.o
.PHONY : src/game/GotchiScene.cpp.o

src/game/GotchiScene.i: src/game/GotchiScene.cpp.i
.PHONY : src/game/GotchiScene.i

# target to preprocess a source file
src/game/GotchiScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiScene.cpp.i
.PHONY : src/game/GotchiScene.cpp.i

src/game/GotchiScene.s: src/game/GotchiScene.cpp.s
.PHONY : src/game/GotchiScene.s

# target to generate assembly for a file
src/game/GotchiScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiScene.cpp.s
.PHONY : src/game/GotchiScene.cpp.s

src/game/GotchiStats.o: src/game/GotchiStats.cpp.o
.PHONY : src/game/GotchiStats.o

# target to build an object file
src/game/GotchiStats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiStats.cpp.o
.PHONY : src/game/GotchiStats.cpp.o

src/game/GotchiStats.i: src/game/GotchiStats.cpp.i
.PHONY : src/game/GotchiStats.i

# target to preprocess a source file
src/game/GotchiStats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiStats.cpp.i
.PHONY : src/game/GotchiStats.cpp.i

src/game/GotchiStats.s: src/game/GotchiStats.cpp.s
.PHONY : src/game/GotchiStats.s

# target to generate assembly for a file
src/game/GotchiStats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiStats.cpp.s
.PHONY : src/game/GotchiStats.cpp.s

src/game/GotchiStatsScene.o: src/game/GotchiStatsScene.cpp.o
.PHONY : src/game/GotchiStatsScene.o

# target to build an object file
src/game/GotchiStatsScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiStatsScene.cpp.o
.PHONY : src/game/GotchiStatsScene.cpp.o

src/game/GotchiStatsScene.i: src/game/GotchiStatsScene.cpp.i
.PHONY : src/game/GotchiStatsScene.i

# target to preprocess a source file
src/game/GotchiStatsScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiStatsScene.cpp.i
.PHONY : src/game/GotchiStatsScene.cpp.i

src/game/GotchiStatsScene.s: src/game/GotchiStatsScene.cpp.s
.PHONY : src/game/GotchiStatsScene.s

# target to generate assembly for a file
src/game/GotchiStatsScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/GotchiStatsScene.cpp.s
.PHONY : src/game/GotchiStatsScene.cpp.s

src/game/HexBoard.o: src/game/HexBoard.cpp.o
.PHONY : src/game/HexBoard.o

# target to build an object file
src/game/HexBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/HexBoard.cpp.o
.PHONY : src/game/HexBoard.cpp.o

src/game/HexBoard.i: src/game/HexBoard.cpp.i
.PHONY : src/game/HexBoard.i

# target to preprocess a source file
src/game/HexBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/HexBoard.cpp.i
.PHONY : src/game/HexBoard.cpp.i

src/game/HexBoard.s: src/game/HexBoard.cpp.s
.PHONY : src/game/HexBoard.s

# target to generate assembly for a file
src/game/HexBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/HexBoard.cpp.s
.PHONY : src/game/HexBoard.cpp.s

src/game/HexViewScene.o: src/game/HexViewScene.cpp.o
.PHONY : src/game/HexViewScene.o

# target to build an object file
src/game/HexViewScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/HexViewScene.cpp.o
.PHONY : src/game/HexViewScene.cpp.o

src/game/HexViewScene.i: src/game/HexViewScene.cpp.i
.PHONY : src/game/HexViewScene.i

# target to preprocess a source file
src/game/HexViewScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/HexViewScene.cpp.i
.PHONY : src/game/HexViewScene.cpp.i

src/game/HexViewScene.s: src/game/HexViewScene.cpp.s
.PHONY : src/game/HexViewScene.s

# target to generate assembly for a file
src/game/HexViewScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/HexViewScene.cpp.s
.PHONY : src/game/HexViewScene.cpp.s

src/game/InputTestScene.o: src/game/InputTestScene.cpp.o
.PHONY : src/game/InputTestScene.o

# target to build an object file
src/game/InputTestScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/InputTestScene.cpp.o
.PHONY : src/game/InputTestScene.cpp.o

src/game/InputTestScene.i: src/game/InputTestScene.cpp.i
.PHONY : src/game/InputTestScene.i

# target to preprocess a source file
src/game/InputTestScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/InputTestScene.cpp.i
.PHONY : src/game/InputTestScene.cpp.i

src/game/InputTestScene.s: src/game/InputTestScene.cpp.s
.PHONY : src/game/InputTestScene.s

# target to generate assembly for a file
src/game/InputTestScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/InputTestScene.cpp.s
.PHONY : src/game/InputTestScene.cpp.s

src/game/MergeController.o: src/game/MergeController.cpp.o
.PHONY : src/game/MergeController.o

# target to build an object file
src/game/MergeController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/game/MergeController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/game/MergeController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/MergeController.cpp.o
.PHONY : src/game/MergeController.cpp.o

src/game/MergeController.i: src/game/MergeController.cpp.i
.PHONY : src/game/MergeController.i

# target to preprocess a source file
src/game/MergeController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/game/MergeController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/game/MergeController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/MergeController.cpp.i
.PHONY : src/game/MergeController.cpp.i

src/game/MergeController.s: src/game/MergeController.cpp.s
.PHONY : src/game/MergeController.s

# target to generate assembly for a file
src/game/MergeController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/game/MergeController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/game/MergeController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/MergeController.cpp.s
.PHONY : src/game/MergeController.cpp.s

src/game/Model3DTestScene.o: src/game/Model3DTestScene.cpp.o
.PHONY : src/game/Model3DTestScene.o

# target to build an object file
src/game/Model3DTestScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/Model3DTestScene.cpp.o
.PHONY : src/game/Model3DTestScene.cpp.o

src/game/Model3DTestScene.i: src/game/Model3DTestScene.cpp.i
.PHONY : src/game/Model3DTestScene.i

# target to preprocess a source file
src/game/Model3DTestScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/Model3DTestScene.cpp.i
.PHONY : src/game/Model3DTestScene.cpp.i

src/game/Model3DTestScene.s: src/game/Model3DTestScene.cpp.s
.PHONY : src/game/Model3DTestScene.s

# target to generate assembly for a file
src/game/Model3DTestScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/Model3DTestScene.cpp.s
.PHONY : src/game/Model3DTestScene.cpp.s

src/game/OfficeScene.o: src/game/OfficeScene.cpp.o
.PHONY : src/game/OfficeScene.o

# target to build an object file
src/game/OfficeScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/OfficeScene.cpp.o
.PHONY : src/game/OfficeScene.cpp.o

src/game/OfficeScene.i: src/game/OfficeScene.cpp.i
.PHONY : src/game/OfficeScene.i

# target to preprocess a source file
src/game/OfficeScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/OfficeScene.cpp.i
.PHONY : src/game/OfficeScene.cpp.i

src/game/OfficeScene.s: src/game/OfficeScene.cpp.s
.PHONY : src/game/OfficeScene.s

# target to generate assembly for a file
src/game/OfficeScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/OfficeScene.cpp.s
.PHONY : src/game/OfficeScene.cpp.s

src/game/PauseMenuOverlay.o: src/game/PauseMenuOverlay.cpp.o
.PHONY : src/game/PauseMenuOverlay.o

# target to build an object file
src/game/PauseMenuOverlay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PauseMenuOverlay.cpp.o
.PHONY : src/game/PauseMenuOverlay.cpp.o

src/game/PauseMenuOverlay.i: src/game/PauseMenuOverlay.cpp.i
.PHONY : src/game/PauseMenuOverlay.i

# target to preprocess a source file
src/game/PauseMenuOverlay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PauseMenuOverlay.cpp.i
.PHONY : src/game/PauseMenuOverlay.cpp.i

src/game/PauseMenuOverlay.s: src/game/PauseMenuOverlay.cpp.s
.PHONY : src/game/PauseMenuOverlay.s

# target to generate assembly for a file
src/game/PauseMenuOverlay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PauseMenuOverlay.cpp.s
.PHONY : src/game/PauseMenuOverlay.cpp.s

src/game/PizzaParlorScene.o: src/game/PizzaParlorScene.cpp.o
.PHONY : src/game/PizzaParlorScene.o

# target to build an object file
src/game/PizzaParlorScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PizzaParlorScene.cpp.o
.PHONY : src/game/PizzaParlorScene.cpp.o

src/game/PizzaParlorScene.i: src/game/PizzaParlorScene.cpp.i
.PHONY : src/game/PizzaParlorScene.i

# target to preprocess a source file
src/game/PizzaParlorScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PizzaParlorScene.cpp.i
.PHONY : src/game/PizzaParlorScene.cpp.i

src/game/PizzaParlorScene.s: src/game/PizzaParlorScene.cpp.s
.PHONY : src/game/PizzaParlorScene.s

# target to generate assembly for a file
src/game/PizzaParlorScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PizzaParlorScene.cpp.s
.PHONY : src/game/PizzaParlorScene.cpp.s

src/game/PlayerActor.o: src/game/PlayerActor.cpp.o
.PHONY : src/game/PlayerActor.o

# target to build an object file
src/game/PlayerActor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PlayerActor.cpp.o
.PHONY : src/game/PlayerActor.cpp.o

src/game/PlayerActor.i: src/game/PlayerActor.cpp.i
.PHONY : src/game/PlayerActor.i

# target to preprocess a source file
src/game/PlayerActor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PlayerActor.cpp.i
.PHONY : src/game/PlayerActor.cpp.i

src/game/PlayerActor.s: src/game/PlayerActor.cpp.s
.PHONY : src/game/PlayerActor.s

# target to generate assembly for a file
src/game/PlayerActor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/PlayerActor.cpp.s
.PHONY : src/game/PlayerActor.cpp.s

src/game/ScenePreviewScene.o: src/game/ScenePreviewScene.cpp.o
.PHONY : src/game/ScenePreviewScene.o

# target to build an object file
src/game/ScenePreviewScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ScenePreviewScene.cpp.o
.PHONY : src/game/ScenePreviewScene.cpp.o

src/game/ScenePreviewScene.i: src/game/ScenePreviewScene.cpp.i
.PHONY : src/game/ScenePreviewScene.i

# target to preprocess a source file
src/game/ScenePreviewScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ScenePreviewScene.cpp.i
.PHONY : src/game/ScenePreviewScene.cpp.i

src/game/ScenePreviewScene.s: src/game/ScenePreviewScene.cpp.s
.PHONY : src/game/ScenePreviewScene.s

# target to generate assembly for a file
src/game/ScenePreviewScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/ScenePreviewScene.cpp.s
.PHONY : src/game/ScenePreviewScene.cpp.s

src/game/SceneSelectScene.o: src/game/SceneSelectScene.cpp.o
.PHONY : src/game/SceneSelectScene.o

# target to build an object file
src/game/SceneSelectScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SceneSelectScene.cpp.o
.PHONY : src/game/SceneSelectScene.cpp.o

src/game/SceneSelectScene.i: src/game/SceneSelectScene.cpp.i
.PHONY : src/game/SceneSelectScene.i

# target to preprocess a source file
src/game/SceneSelectScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SceneSelectScene.cpp.i
.PHONY : src/game/SceneSelectScene.cpp.i

src/game/SceneSelectScene.s: src/game/SceneSelectScene.cpp.s
.PHONY : src/game/SceneSelectScene.s

# target to generate assembly for a file
src/game/SceneSelectScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SceneSelectScene.cpp.s
.PHONY : src/game/SceneSelectScene.cpp.s

src/game/SchoolScene.o: src/game/SchoolScene.cpp.o
.PHONY : src/game/SchoolScene.o

# target to build an object file
src/game/SchoolScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SchoolScene.cpp.o
.PHONY : src/game/SchoolScene.cpp.o

src/game/SchoolScene.i: src/game/SchoolScene.cpp.i
.PHONY : src/game/SchoolScene.i

# target to preprocess a source file
src/game/SchoolScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SchoolScene.cpp.i
.PHONY : src/game/SchoolScene.cpp.i

src/game/SchoolScene.s: src/game/SchoolScene.cpp.s
.PHONY : src/game/SchoolScene.s

# target to generate assembly for a file
src/game/SchoolScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SchoolScene.cpp.s
.PHONY : src/game/SchoolScene.cpp.s

src/game/SpriteTestScene.o: src/game/SpriteTestScene.cpp.o
.PHONY : src/game/SpriteTestScene.o

# target to build an object file
src/game/SpriteTestScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SpriteTestScene.cpp.o
.PHONY : src/game/SpriteTestScene.cpp.o

src/game/SpriteTestScene.i: src/game/SpriteTestScene.cpp.i
.PHONY : src/game/SpriteTestScene.i

# target to preprocess a source file
src/game/SpriteTestScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SpriteTestScene.cpp.i
.PHONY : src/game/SpriteTestScene.cpp.i

src/game/SpriteTestScene.s: src/game/SpriteTestScene.cpp.s
.PHONY : src/game/SpriteTestScene.s

# target to generate assembly for a file
src/game/SpriteTestScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/SpriteTestScene.cpp.s
.PHONY : src/game/SpriteTestScene.cpp.s

src/game/StorySequencer.o: src/game/StorySequencer.cpp.o
.PHONY : src/game/StorySequencer.o

# target to build an object file
src/game/StorySequencer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/game/StorySequencer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/game/StorySequencer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/StorySequencer.cpp.o
.PHONY : src/game/StorySequencer.cpp.o

src/game/StorySequencer.i: src/game/StorySequencer.cpp.i
.PHONY : src/game/StorySequencer.i

# target to preprocess a source file
src/game/StorySequencer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/game/StorySequencer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/game/StorySequencer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/StorySequencer.cpp.i
.PHONY : src/game/StorySequencer.cpp.i

src/game/StorySequencer.s: src/game/StorySequencer.cpp.s
.PHONY : src/game/StorySequencer.s

# target to generate assembly for a file
src/game/StorySequencer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/src/game/StorySequencer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/src/game/StorySequencer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/StorySequencer.cpp.s
.PHONY : src/game/StorySequencer.cpp.s

src/game/TherapistOfficeScene.o: src/game/TherapistOfficeScene.cpp.o
.PHONY : src/game/TherapistOfficeScene.o

# target to build an object file
src/game/TherapistOfficeScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TherapistOfficeScene.cpp.o
.PHONY : src/game/TherapistOfficeScene.cpp.o

src/game/TherapistOfficeScene.i: src/game/TherapistOfficeScene.cpp.i
.PHONY : src/game/TherapistOfficeScene.i

# target to preprocess a source file
src/game/TherapistOfficeScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TherapistOfficeScene.cpp.i
.PHONY : src/game/TherapistOfficeScene.cpp.i

src/game/TherapistOfficeScene.s: src/game/TherapistOfficeScene.cpp.s
.PHONY : src/game/TherapistOfficeScene.s

# target to generate assembly for a file
src/game/TherapistOfficeScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TherapistOfficeScene.cpp.s
.PHONY : src/game/TherapistOfficeScene.cpp.s

src/game/TitleScene.o: src/game/TitleScene.cpp.o
.PHONY : src/game/TitleScene.o

# target to build an object file
src/game/TitleScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TitleScene.cpp.o
.PHONY : src/game/TitleScene.cpp.o

src/game/TitleScene.i: src/game/TitleScene.cpp.i
.PHONY : src/game/TitleScene.i

# target to preprocess a source file
src/game/TitleScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TitleScene.cpp.i
.PHONY : src/game/TitleScene.cpp.i

src/game/TitleScene.s: src/game/TitleScene.cpp.s
.PHONY : src/game/TitleScene.s

# target to generate assembly for a file
src/game/TitleScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TitleScene.cpp.s
.PHONY : src/game/TitleScene.cpp.s

src/game/TomSceneActor.o: src/game/TomSceneActor.cpp.o
.PHONY : src/game/TomSceneActor.o

# target to build an object file
src/game/TomSceneActor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TomSceneActor.cpp.o
.PHONY : src/game/TomSceneActor.cpp.o

src/game/TomSceneActor.i: src/game/TomSceneActor.cpp.i
.PHONY : src/game/TomSceneActor.i

# target to preprocess a source file
src/game/TomSceneActor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TomSceneActor.cpp.i
.PHONY : src/game/TomSceneActor.cpp.i

src/game/TomSceneActor.s: src/game/TomSceneActor.cpp.s
.PHONY : src/game/TomSceneActor.s

# target to generate assembly for a file
src/game/TomSceneActor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game/TomSceneActor.cpp.s
.PHONY : src/game/TomSceneActor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/TestGrimeShader.o: tests/TestGrimeShader.cpp.o
.PHONY : tests/TestGrimeShader.o

# target to build an object file
tests/TestGrimeShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/TestGrimeShader.cpp.o
.PHONY : tests/TestGrimeShader.cpp.o

tests/TestGrimeShader.i: tests/TestGrimeShader.cpp.i
.PHONY : tests/TestGrimeShader.i

# target to preprocess a source file
tests/TestGrimeShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/TestGrimeShader.cpp.i
.PHONY : tests/TestGrimeShader.cpp.i

tests/TestGrimeShader.s: tests/TestGrimeShader.cpp.s
.PHONY : tests/TestGrimeShader.s

# target to generate assembly for a file
tests/TestGrimeShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/TestGrimeShader.cpp.s
.PHONY : tests/TestGrimeShader.cpp.s

tests/TestMergeController.o: tests/TestMergeController.cpp.o
.PHONY : tests/TestMergeController.o

# target to build an object file
tests/TestMergeController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/tests/TestMergeController.cpp.o
.PHONY : tests/TestMergeController.cpp.o

tests/TestMergeController.i: tests/TestMergeController.cpp.i
.PHONY : tests/TestMergeController.i

# target to preprocess a source file
tests/TestMergeController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/tests/TestMergeController.cpp.i
.PHONY : tests/TestMergeController.cpp.i

tests/TestMergeController.s: tests/TestMergeController.cpp.s
.PHONY : tests/TestMergeController.s

# target to generate assembly for a file
tests/TestMergeController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_controller.dir/build.make CMakeFiles/test_merge_controller.dir/tests/TestMergeController.cpp.s
.PHONY : tests/TestMergeController.cpp.s

tests/TestStorySequencer.o: tests/TestStorySequencer.cpp.o
.PHONY : tests/TestStorySequencer.o

# target to build an object file
tests/TestStorySequencer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/tests/TestStorySequencer.cpp.o
.PHONY : tests/TestStorySequencer.cpp.o

tests/TestStorySequencer.i: tests/TestStorySequencer.cpp.i
.PHONY : tests/TestStorySequencer.i

# target to preprocess a source file
tests/TestStorySequencer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/tests/TestStorySequencer.cpp.i
.PHONY : tests/TestStorySequencer.cpp.i

tests/TestStorySequencer.s: tests/TestStorySequencer.cpp.s
.PHONY : tests/TestStorySequencer.s

# target to generate assembly for a file
tests/TestStorySequencer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_story_sequencer.dir/build.make CMakeFiles/test_story_sequencer.dir/tests/TestStorySequencer.cpp.s
.PHONY : tests/TestStorySequencer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... game-web"
	@echo "... raylib-web"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... game"
	@echo "... glfw"
	@echo "... raylib"
	@echo "... test_merge_controller"
	@echo "... test_story_sequencer"
	@echo "... tests"
	@echo "... raylib/src/raudio.o"
	@echo "... raylib/src/raudio.i"
	@echo "... raylib/src/raudio.s"
	@echo "... raylib/src/rcore.o"
	@echo "... raylib/src/rcore.i"
	@echo "... raylib/src/rcore.s"
	@echo "... raylib/src/rmodels.o"
	@echo "... raylib/src/rmodels.i"
	@echo "... raylib/src/rmodels.s"
	@echo "... raylib/src/rshapes.o"
	@echo "... raylib/src/rshapes.i"
	@echo "... raylib/src/rshapes.s"
	@echo "... raylib/src/rtext.o"
	@echo "... raylib/src/rtext.i"
	@echo "... raylib/src/rtext.s"
	@echo "... raylib/src/rtextures.o"
	@echo "... raylib/src/rtextures.i"
	@echo "... raylib/src/rtextures.s"
	@echo "... src/effects/CityWindowEffect.o"
	@echo "... src/effects/CityWindowEffect.i"
	@echo "... src/effects/CityWindowEffect.s"
	@echo "... src/effects/GrimeShader.o"
	@echo "... src/effects/GrimeShader.i"
	@echo "... src/effects/GrimeShader.s"
	@echo "... src/effects/JetMesh.o"
	@echo "... src/effects/JetMesh.i"
	@echo "... src/effects/JetMesh.s"
	@echo "... src/effects/LitShader.o"
	@echo "... src/effects/LitShader.i"
	@echo "... src/effects/LitShader.s"
	@echo "... src/effects/MoonEffect.o"
	@echo "... src/effects/MoonEffect.i"
	@echo "... src/effects/MoonEffect.s"
	@echo "... src/effects/SchoolSkyEffect.o"
	@echo "... src/effects/SchoolSkyEffect.i"
	@echo "... src/effects/SchoolSkyEffect.s"
	@echo "... src/effects/StarfieldEffect.o"
	@echo "... src/effects/StarfieldEffect.i"
	@echo "... src/effects/StarfieldEffect.s"
	@echo "... src/engine/AssetPack.o"
	@echo "... src/engine/AssetPack.i"
	@echo "... src/engine/AssetPack.s"
	@echo "... src/engine/Button.o"
	@echo "... src/engine/Button.i"
	@echo "... src/engine/Button.s"
	@echo "... src/engine/DialogBox.o"
	@echo "... src/engine/DialogBox.i"
	@echo "... src/engine/DialogBox.s"
	@echo "... src/engine/GameState.o"
	@echo "... src/engine/GameState.i"
	@echo "... src/engine/GameState.s"
	@echo "... src/engine/HexTile.o"
	@echo "... src/engine/HexTile.i"
	@echo "... src/engine/HexTile.s"
	@echo "... src/engine/HexWorld.o"
	@echo "... src/engine/HexWorld.i"
	@echo "... src/engine/HexWorld.s"
	@echo "... src/engine/SaveManager.o"
	@echo "... src/engine/SaveManager.i"
	@echo "... src/engine/SaveManager.s"
	@echo "... src/engine/Scene.o"
	@echo "... src/engine/Scene.i"
	@echo "... src/engine/Scene.s"
	@echo "... src/engine/SceneActor.o"
	@echo "... src/engine/SceneActor.i"
	@echo "... src/engine/SceneActor.s"
	@echo "... src/engine/SceneCamera.o"
	@echo "... src/engine/SceneCamera.i"
	@echo "... src/engine/SceneCamera.s"
	@echo "... src/engine/SceneInputHandler.o"
	@echo "... src/engine/SceneInputHandler.i"
	@echo "... src/engine/SceneInputHandler.s"
	@echo "... src/engine/SceneManager.o"
	@echo "... src/engine/SceneManager.i"
	@echo "... src/engine/SceneManager.s"
	@echo "... src/engine/TileType.o"
	@echo "... src/engine/TileType.i"
	@echo "... src/engine/TileType.s"
	@echo "... src/events/EventBus.o"
	@echo "... src/events/EventBus.i"
	@echo "... src/events/EventBus.s"
	@echo "... src/game/ApartmentScene.o"
	@echo "... src/game/ApartmentScene.i"
	@echo "... src/game/ApartmentScene.s"
	@echo "... src/game/BossScene.o"
	@echo "... src/game/BossScene.i"
	@echo "... src/game/BossScene.s"
	@echo "... src/game/ControlsOverlay.o"
	@echo "... src/game/ControlsOverlay.i"
	@echo "... src/game/ControlsOverlay.s"
	@echo "... src/game/GameScene.o"
	@echo "... src/game/GameScene.i"
	@echo "... src/game/GameScene.s"
	@echo "... src/game/Gotchi.o"
	@echo "... src/game/Gotchi.i"
	@echo "... src/game/Gotchi.s"
	@echo "... src/game/GotchiMood.o"
	@echo "... src/game/GotchiMood.i"
	@echo "... src/game/GotchiMood.s"
	@echo "... src/game/GotchiScene.o"
	@echo "... src/game/GotchiScene.i"
	@echo "... src/game/GotchiScene.s"
	@echo "... src/game/GotchiStats.o"
	@echo "... src/game/GotchiStats.i"
	@echo "... src/game/GotchiStats.s"
	@echo "... src/game/GotchiStatsScene.o"
	@echo "... src/game/GotchiStatsScene.i"
	@echo "... src/game/GotchiStatsScene.s"
	@echo "... src/game/HexBoard.o"
	@echo "... src/game/HexBoard.i"
	@echo "... src/game/HexBoard.s"
	@echo "... src/game/HexViewScene.o"
	@echo "... src/game/HexViewScene.i"
	@echo "... src/game/HexViewScene.s"
	@echo "... src/game/InputTestScene.o"
	@echo "... src/game/InputTestScene.i"
	@echo "... src/game/InputTestScene.s"
	@echo "... src/game/MergeController.o"
	@echo "... src/game/MergeController.i"
	@echo "... src/game/MergeController.s"
	@echo "... src/game/Model3DTestScene.o"
	@echo "... src/game/Model3DTestScene.i"
	@echo "... src/game/Model3DTestScene.s"
	@echo "... src/game/OfficeScene.o"
	@echo "... src/game/OfficeScene.i"
	@echo "... src/game/OfficeScene.s"
	@echo "... src/game/PauseMenuOverlay.o"
	@echo "... src/game/PauseMenuOverlay.i"
	@echo "... src/game/PauseMenuOverlay.s"
	@echo "... src/game/PizzaParlorScene.o"
	@echo "... src/game/PizzaParlorScene.i"
	@echo "... src/game/PizzaParlorScene.s"
	@echo "... src/game/PlayerActor.o"
	@echo "... src/game/PlayerActor.i"
	@echo "... src/game/PlayerActor.s"
	@echo "... src/game/ScenePreviewScene.o"
	@echo "... src/game/ScenePreviewScene.i"
	@echo "... src/game/ScenePreviewScene.s"
	@echo "... src/game/SceneSelectScene.o"
	@echo "... src/game/SceneSelectScene.i"
	@echo "... src/game/SceneSelectScene.s"
	@echo "... src/game/SchoolScene.o"
	@echo "... src/game/SchoolScene.i"
	@echo "... src/game/SchoolScene.s"
	@echo "... src/game/SpriteTestScene.o"
	@echo "... src/game/SpriteTestScene.i"
	@echo "... src/game/SpriteTestScene.s"
	@echo "... src/game/StorySequencer.o"
	@echo "... src/game/StorySequencer.i"
	@echo "... src/game/StorySequencer.s"
	@echo "... src/game/TherapistOfficeScene.o"
	@echo "... src/game/TherapistOfficeScene.i"
	@echo "... src/game/TherapistOfficeScene.s"
	@echo "... src/game/TitleScene.o"
	@echo "... src/game/TitleScene.i"
	@echo "... src/game/TitleScene.s"
	@echo "... src/game/TomSceneActor.o"
	@echo "... src/game/TomSceneActor.i"
	@echo "... src/game/TomSceneActor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/TestGrimeShader.o"
	@echo "... tests/TestGrimeShader.i"
	@echo "... tests/TestGrimeShader.s"
	@echo "... tests/TestMergeController.o"
	@echo "... tests/TestMergeController.i"
	@echo "... tests/TestMergeController.s"
	@echo "... tests/TestStorySequencer.o"
	@echo "... tests/TestStorySequencer.i"
	@echo "... tests/TestStorySequencer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

